src/objects/BoxDefaults__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for Box Integration</description>
    <fields>
        <fullName>AuthToken__c</fullName>
        <description>Authentication Token for Box</description>
        <label>Auth Token</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Box Defaults</label>
</CustomObject>

src/classes/BoxAuthController.cls
public class BoxAuthController {

    public static String authToken= System.currentPagereference().getParameters().get('auth_token');
    
    public boxAuthController () {
    }
    
    public PageReference updateBoxAuth() {
        if (authToken != null) { 
            
            BoxDefaults__c s = BoxDefaults__c.getValues(UserInfo.getUserId());
            if (s == null) {
                s = new BoxDefaults__c(setupownerid = UserInfo.getUserId(), authtoken__c = authToken);
            } else {
                s.authtoken__c = authToken;
            }
            
            try {
                Database.UpsertResult result = Database.upsert(s);
            } catch (System.DMLException e) {
                System.Debug(e);
            }
        }
        return null;
    }

}